# Name : Vansh Kolte | C-63
## Date- 027/08/2024
### AIM: Apply dimensionality reduction technique
### Principle Component Analysis (PCA) on digit classification dataset and then
### apply logistic regression algorithm to generate the model.

In [23]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 


In [4]:
import warnings
warnings.filterwarnings("ignore")

## Import Inbuilt dataset

In [3]:
from sklearn.datasets import load_digits

In [5]:
dg = load_digits()

In [7]:
dg.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [9]:
print(dg['DESCR'])

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [17]:
# GET the column names
print(dg['feature_names'])

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1', 'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6', 'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3', 'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7']


In [35]:
# store feature and target in variable 
X= dg.data
y = dg.target

In [27]:
df = pd.DataFrame(dg['data'],columns= dg['feature_names'])

In [29]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [31]:
df.isnull().sum()

pixel_0_0    0
pixel_0_1    0
pixel_0_2    0
pixel_0_3    0
pixel_0_4    0
            ..
pixel_7_3    0
pixel_7_4    0
pixel_7_5    0
pixel_7_6    0
pixel_7_7    0
Length: 64, dtype: int64

## Logistic Regression

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 6)

In [39]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1347, 64), (450, 64), (1347,), (450,))

In [41]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [43]:
logreg.fit(X_train,y_train)

C:\Users\cse\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [45]:
y_pred = logreg.predict(X_test)
y_pred

array([1, 9, 6, 0, 8, 5, 7, 8, 4, 2, 9, 6, 2, 6, 0, 7, 4, 3, 1, 3, 7, 2,
       2, 2, 0, 6, 2, 6, 5, 0, 0, 2, 3, 3, 5, 6, 6, 7, 6, 5, 7, 6, 2, 8,
       2, 7, 4, 7, 6, 6, 6, 1, 6, 8, 6, 4, 1, 2, 0, 2, 4, 3, 4, 0, 4, 7,
       5, 4, 1, 9, 5, 0, 4, 1, 0, 0, 5, 8, 3, 0, 0, 2, 8, 0, 2, 1, 4, 0,
       8, 2, 9, 9, 1, 9, 5, 8, 4, 0, 4, 6, 0, 4, 8, 1, 1, 4, 7, 1, 6, 7,
       5, 0, 5, 0, 5, 4, 3, 1, 4, 0, 1, 4, 5, 5, 3, 1, 2, 1, 1, 0, 3, 7,
       1, 4, 9, 6, 8, 4, 9, 8, 7, 4, 4, 6, 6, 2, 3, 9, 3, 7, 3, 5, 3, 8,
       5, 1, 2, 4, 1, 8, 8, 2, 6, 9, 0, 5, 2, 3, 5, 4, 7, 1, 4, 8, 3, 0,
       4, 7, 6, 5, 0, 1, 2, 4, 9, 9, 4, 2, 2, 8, 5, 3, 2, 9, 0, 4, 8, 2,
       3, 4, 4, 0, 5, 7, 0, 2, 3, 9, 2, 1, 8, 5, 7, 8, 7, 8, 0, 2, 9, 7,
       7, 7, 0, 0, 2, 4, 2, 4, 8, 7, 2, 6, 2, 0, 2, 2, 9, 2, 5, 7, 5, 6,
       0, 5, 6, 5, 3, 0, 9, 6, 2, 5, 2, 4, 3, 7, 4, 1, 9, 2, 3, 3, 1, 9,
       8, 9, 3, 3, 5, 2, 4, 1, 8, 2, 5, 9, 6, 0, 7, 4, 4, 8, 2, 0, 9, 8,
       5, 3, 7, 9, 0, 5, 7, 2, 1, 6, 5, 8, 1, 3, 1,

In [58]:
from sklearn import metrics

In [60]:
metrics.accuracy_score(y_test, y_pred)

0.9511111111111111

In [62]:
metrics.confusion_matrix(y_test, y_pred)

array([[51,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 39,  0,  0,  1,  0,  0,  0,  1,  1],
       [ 0,  0, 51,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2, 36,  0,  0,  0,  0,  1,  1],
       [ 1,  0,  0,  0, 50,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0, 50,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0, 43,  0,  1,  0],
       [ 0,  0,  0,  2,  1,  0,  0, 40,  0,  1],
       [ 0,  0,  2,  0,  0,  0,  0,  0, 37,  0],
       [ 0,  0,  0,  0,  0,  1,  0,  1,  2, 31]], dtype=int64)

In [64]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97        52
           1       0.97      0.93      0.95        42
           2       0.91      1.00      0.95        51
           3       0.95      0.90      0.92        40
           4       0.96      0.98      0.97        51
           5       0.98      0.98      0.98        51
           6       1.00      0.96      0.98        45
           7       0.98      0.91      0.94        44
           8       0.88      0.95      0.91        39
           9       0.91      0.89      0.90        35

    accuracy                           0.95       450
   macro avg       0.95      0.95      0.95       450
weighted avg       0.95      0.95      0.95       450



## Apply PCA

In [139]:
from sklearn.decomposition import PCA

# Initialize PCA
pca = PCA(n_components=8)  # Retain 95% of the variance
X_pca = pca.fit_transform(df)

print(f"Original number of features: {X.shape[1]}")
print(f"Reduced number of features: {X_pca.shape[1]}")


Original number of features: 64
Reduced number of features: 8


In [141]:
X_pca

array([[-1.25924512e+00,  2.12746666e+01, -9.46250758e+00, ...,
        -7.44055148e+00,  3.25830683e+00,  2.63824838e+00],
       [ 7.95754366e+00, -2.07687756e+01,  4.43932218e+00, ...,
        -6.48268863e+00,  2.13045888e+00, -4.64745603e+00],
       [ 6.99190752e+00, -9.95589775e+00,  2.95849997e+00, ...,
        -4.51175101e+00,  1.83644634e+00, -1.64238242e+01],
       ...,
       [ 1.08011945e+01, -6.96016938e+00,  5.59928960e+00, ...,
        -1.23772169e+01, -4.49684105e+00, -7.45016983e+00],
       [-4.87199208e+00,  1.24238350e+01, -1.01705863e+01, ...,
        -4.23885318e-03, -2.98994139e+00, -4.30691706e+00],
       [-3.44463049e-01,  6.36566311e+00,  1.07734874e+01, ...,
        -3.05156563e+00, -1.16201846e+01,  6.40534481e-01]])

In [153]:
from sklearn.model_selection import train_test_split
X_train_pca,X_test,y_train,y_test = train_test_split(X_pca,y,random_state = 6)

In [155]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [157]:
logreg.fit(X_train_pca,y_train)

C:\Users\cse\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [159]:
metrics.accuracy_score(y_test, y_pred)

0.92